<?php
// $Id$
/**
*@file
* This file is created to show custom pager creation in drupal.
* 

*/


/**
* Implementation of hook_menu()
*/

function eventalter_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
  global $user;
  $singleNodeType = 'event';
  if($node->type == $singleNodeType)
	{
  switch ($op) {
				case 'delete':
				  {
				 
					drupal_set_message('You just deleted event node.');
				  
				   break;
				  }
				  case 'update':
				  {
				 
					drupal_set_message('You just updated event node.');
				  
				   break;
				  }
				case 'view':
						{

							// append the following text to the body
						 $node->content['body']['#value'] .= '<b>body added by event module using nodeapi!<b>';
						   break;
						}
				case 'prepare':
						{
							$sql ="SELECT COUNT(*) FROM {node} WHERE node.type='%s' and node.uid=%d";
							$res = db_result(db_query($sql, $singleNodeType, $user->uid));
							if($res)
							{
								// set a message
								 drupal_set_message("you have created $res node of type $singleNodeType");
							  // redirect the user
								//  drupal_goto('<front>');
							}
							else
						   {
								// set a message
								drupal_set_message("you have created $res node of type $singleNodeType");
							  // redirect the user
								  //drupal_goto('<front>');
						   }

						   break;
						}
                 }
    }
}