  <?php
// $Id$
/**
*@file
* This file is created to show custom form creation in drupal.
*/


/**
* Implementation of hook_menu()
*/



function content_news_event_menu()
{
	$items = array();
	$items['news-event'] = array( 'title' => t('News and Event'),
		                           'page callback' => 'my_custom_news_event',
					   'access arguments' => array('access content'),
					   'type' =>MENU_CALLBACK,
									
		                          );
	
	return $items;
}

function my_custom_news_event()
{
       $output ='';
	global $_domain;
        $dom_id = $_domain['domain_id'];
        $site_name = $_domain['sitename'];
        $site_base_url =  $_domain['path'];

	$output .= drupal_get_form('news_event_form');

	//$output .= 'Doimain id:'.$dom_id.'<br/>  Site Name:'.$site_name.'<br/> Site Base Url:'.$site_base_url;

	$to_get_date = $_GET['to'];
	$from_get_date = $_GET['from'];
	if($dom_id==0)
	{
	  $hospital_get = $_GET['hospital'];
	}
	else
	{
	  $hospital_get = $dom_id ;
	}

	

	if($to_get_date)
	{

			 if(strtotime($from_get_date) > strtotime($to_get_date) || strtotime($from_get_date) == strtotime($to_get_date))
			 {
			   
			   form_set_error('from-date', t('From date should be less than To Date'));
			    
			    
				   
			 }
			 elseif($hospital_get=='select')
			 {
				 form_set_error('hospital', t('please Select a hospital'));
			 }

			 else
			 {
			    $output .= show_data_news_event($from_get_date, $to_get_date, $hospital_get);
			 }

	}

	else
	    {
	       $output .= show_all_data_news_event($_domain['domain_id']);
	       
	    }


	 return $output;
	
}

function news_event_form()
{
   global $_domain;
   $hosp = array();
   $hosp['select']='select';
   $res =db_query("SELECT domain_id, sitename FROM domain ORDER BY domain_id");
   while($row = db_fetch_object($res))
   {
	$hosp[$row->domain_id]=$row->sitename;
   }
  
  $form['from-date'] = array(
                            '#title' => t('From'),
			    '#required' => TRUE,
			    '#type'=> 'date',
			    '#weight' => 1,
			  );
$form['to-date'] = array(
                            '#title' => t('To'),
			    '#required' => TRUE,
			    '#type'=> 'date',
			    '#weight' => 2,
			  );
if($_domain['domain_id']==0)
{
	$form['hospital'] = array (
				      '#title'=> t('Hospital'),
				      '#required' => TRUE,
				       '#type'=> 'select',
				       '#options'=> $hosp,
				       '#weight' => 3,
				     );
}
 $form['submit'] = array(
			 '#type' => 'submit',
			 '#value' =>'Search',
			 '#weight' => 4,
                        );



  return $form;
}


function news_event_form_validate($form, &$form_state)
{
  
}

function news_event_form_submit($form, &$form_state)
{

     
       $from_date = $form_state['values']['from-date'];

		   $from_day=$form_state['values']['from-date'][day];
		   $from_month=$form_state['values']['from-date'][month];
		   $from_year=$form_state['values']['from-date'][year];

	   $formated_from_date = $from_year."-". $from_month."-".$from_day;

	   $to_date = $form_state['values']['to-date'];

		$to_day=$form_state['values']['to-date'][day];
		$to_month=$form_state['values']['to-date'][month];
		$to_year=$form_state['values']['to-date'][year];

	$formated_to_date = $to_year."-". $to_month."-".$to_day;

        $q = array();
	$q['from'] = $formated_from_date;
	$q['to'] = $formated_to_date;
	$q['hospital'] = $form_state['values']['hospital'];
	//$querystring = http_build_query($q);

	


	drupal_goto("news-event", $q);

	
	
 
  
}

function show_data_news_event($a, $b, $c)
{

   $output = '';

       $dom=db_result(db_query("SELECT sitename FROM domain WHERE domain_id=%d",$c));
	$d1 = date('F j, Y', strtotime($a));
	$d2 = date('F j, Y', strtotime($b));
        
	drupal_set_message(t('Following are the results of domain %domain between date %d1 and %d2.', array('%domain'=>$dom, '%d1'=>$d1, '%d2'=>$d2)));

   $node_data ='';
   $frm = $a."T00:00:00";
   $t = $b."T00:00:00";
   $sql_count = "SELECT count(*) FROM node AS n JOIN domain_source AS ds ON n.nid = ds.nid JOIN content_type_news_and_event AS ctne ON ctne.nid=n.nid WHERE ds.domain_id=$c AND ctne.field_news_and_event_date_value BETWEEN '$frm' AND '$t'";

   $rec = db_result(db_query($sql_count));
   
   if($rec==0)
   {
     $output .= "<div class='no-record'>No Record Found</div>";
   }
   else
   {
		   $sql= "SELECT n.nid FROM node AS n JOIN domain_source AS ds ON n.nid = ds.nid JOIN content_type_news_and_event AS ctne ON ctne.nid=n.nid WHERE ds.domain_id=$c AND ctne.field_news_and_event_date_value BETWEEN '$frm' AND '$t'";

		    $res = pager_query($sql,2,0,$sql_count);
		   
		   
		   while($row = db_fetch_object( $res))
		   {
		     $xy = node_load($row->nid);
		     $output .="<div class='mediea-room-text'>";
		     $output .="<p><a href='".$xy->field_news_and_event_pdf[0][filepath]."' target='_blank'>".$xy->title."</a></p>";
		     $output .="<h5>".date('F j, Y', strtotime($xy->field_news_and_event_date[0][value]))."</h5>";
		     $output .="<h6>".db_result(db_query("SELECT sitename FROM domain WHERE domain_id=%d",$xy->domain_source))."</h6>";
		      $output .="</div>";
		     
		   }

		   $output .= "<div class='pagination-box'>".theme('pager', NULL, 2, 0)."</div>";
  }
    return $output;
}


/**** show all data **/

function show_all_data_news_event($c)
{
                
                if($c==0)
		{
			$sql_count = "SELECT count(*) FROM node AS n JOIN domain_source AS ds ON n.nid = ds.nid JOIN content_type_news_and_event AS ctne ON ctne.nid=n.nid";
		 }
		 else
		 {
		    $sql_count = "SELECT count(*) FROM node AS n JOIN domain_source AS ds ON n.nid = ds.nid JOIN content_type_news_and_event AS ctne ON ctne.nid=n.nid WHERE ds.domain_id=$c";
		 }

		   $rec = db_result(db_query($sql_count));
		   
		   if($rec==0)
		   {
		     $output .= "<div class='no-record'>No Record Found</div>";
		   }
		   else
		   {
		                  if($c==0)
					{
						 $sql= "SELECT n.nid FROM node AS n JOIN domain_source AS ds ON n.nid = ds.nid JOIN content_type_news_and_event AS ctne ON ctne.nid=n.nid";
					 }
					 else
					 {
					    $sql= "SELECT n.nid FROM node AS n JOIN domain_source AS ds ON n.nid = ds.nid JOIN content_type_news_and_event AS ctne ON ctne.nid=n.nid WHERE ds.domain_id=$c";
					 }
				  
                                        
				    $res = pager_query($sql,2,0,$sql_count);
				   
				   
				   while($row = db_fetch_object( $res))
				   {
				      $xy = node_load($row->nid);
				     $output .="<div class='mediea-room-text'>";
				     $output .="<p><a href='".$xy->field_news_and_event_pdf[0][filepath]."' target='_blank'>".$xy->title."</a></p>";
				     $output .="<h5>".date('F j, Y', strtotime($xy->field_news_and_event_date[0][value]))."</h5>";
				     $output .="<h6>".db_result(db_query("SELECT sitename FROM domain WHERE domain_id=%d",$xy->domain_source))."</h6>";
				      $output .="</div>";
				     
				   }

				   $output .= "<div class='pagination-box'>".theme('pager', NULL, 2, 0)."</div>";
		  }
		    return $output;
}