<?php
// $Id$
/**
*@file
* This file is created to implement pryer partenr functionality.
* 

*/

/**
* Implementation of hook_perm()
*/



/**
* Implementation of hook_menu()
*/



function custom_pp_menu()
{
	$items = array();
	$items['prayer-pat'] = array(
                                     'title' => t('Prayer Pat'),
		                             'page callback' => 'prayer_pat_data',
                                     'access arguments' => array('access content'), 
								     'type' =>MENU_NORMAL_ITEM,
									
		                          );
   $items['prayer-pat/autocomplete'] = array(
                                     'title' => t('Prayer Pat Autocomplete'),
                                     'page callback' => 'prayer_pat_data_autocomplete',
                                     'access arguments' => array('access content'), 
								     'type' =>MENU_NORMAL_ITEM,
									
		                          );
  

	
	
	return $items;
}

/**
* callback of prayer partner page
*/
function prayer_pat_data()
{
    $output= '';
    $output .= drupal_get_form('prayer_pat_data_form');
    return $output;
}

/**
* Definition of prayer partent form
*/

function prayer_pat_data_form()
{
    $options = array('select'=>'select','red'=> 'Red', 'blue'=> 'Blue', 'green'=> 'Green');
    $form = array();
    $form['auto-node-text'] = array(
                                '#title' => t('Enter Node Title'),
                                '#type' => 'textfield',
                                '#required' => TRUE,
                                '#weight' => 1,
                                '#autocomplete_path' => 'prayer-pat/autocomplete'
                               );
    $form['auto-node-submit'] = array(
                                '#type'  => 'submit',
                                '#weight' =>2,
                                '#value' => t('Submit')
                                );
    return $form;
}

/**
* prayar partner form validation
*/

function prayer_pat_data_form_validate($form, &$form_state)
{
   
    if($form_state['values']['pp-select']=='select')
    {
     form_set_error('pp-select', t('Please select your prayer partner'));
    }
    
}

/** 
* prayer partner form submition
*/

function prayer_pat_data_form_submit($form, &$form_state)
{
    drupal_set_message(t('You prayer pat request has been sent'));
}

function prayer_pat_data_autocomplete($string)
{
     $items = array();  
     
  
  $result = db_query("SELECT nid, title FROM {node} WHERE status = 1 AND LOWER(title) LIKE LOWER('%s%%')",  $string);
  
  while($obj = db_fetch_object($result)) {
    $items[$obj->nid] = check_plain($obj->title);
    
  }
  print drupal_to_js($items); 
  exit();
}