<?php
// $Id$


/**
*@file
*  This module is created to show various types of data  related to Organization.
*/

  global $option;
  $option = array();

  function financial_report_perm()
  {
	  return array('view financial report');
  }

/**
* Implementation of hook_menu()
*/

  function financial_report_menu()
  {
    $items = array();

    $items['reports/financial-report/businessad']= array(
					 'title' => t('Financial reports of Business ads'),
					 'page callback' => 'fin_bussad_cal',
					 'access arguments' => array('view financial report'),
					 'type' => MENU_CALLBACK,
					);

	


    return $items;
  }

 
 function fin_bussad_cal()
  {
    
     $output  = '';
     $output .= drupal_get_form('fin_bussad_form');

     /*********  output area ******/

     $from_date='hi';
	 $to_date = 'bye';
     
	 if($from_date && $to_date)
	  {
       $output .= theme('financila_businees_ad_report', $from_date, $to_date);
	  }
         
     return  $output;
  }

  

   /**
   * Implementation of hook_theme()
   */

   function financial_report_theme()
   {
     return array(
                        'financila_businees_ad_report' => array(
		                'arguments' => array('from_date'=> NULL, 'to_date'=> NULL),
					    'template'  => 'financila-businees-ad-report',
					  ),

		               
                  );
   }

/**
* Form definition Business ads
*/


  function fin_bussad_form()
  {
	  drupal_add_css(drupal_get_path('module', 'financial_report') .'/financial_report.css');

    
    $form['bussad-from'] = array(
				 '#title' => t('From'),
				 '#required' => TRUE,
				 '#type' => 'date_popup',
				 '#date_format' => 'Y-m-d',
                 '#date_year_range' => '-20:+20',
				 '#weight' => 1,
				);
	$form['bussad-to'] = array(
				 '#title' => t('To'),
				 '#required' => TRUE,
				 '#type' => 'date_popup',
				 '#date_format' => 'Y-m-d',
                 '#date_year_range' => '-20:+20',
				 '#weight' => 2,
				);
   $form[sumit] = array(
                         '#type' => 'submit',
			             '#value' => 'Apply',
			             '#weight' => 3,
			);

   return $form;

  }


  function fin_bussad_form_validate($form, &$form_state)
  {
     

    if($form_state['values']['bussad-from'])
    {
	form_set_error('bussad-from', 'Please select  From Date');
	drupal_goto("reports/financial-report/businessad");
    }

	if($form_state['values']['bussad-to'])
    {
	form_set_error('bussad-to', 'Please select  To Date');
	drupal_goto("reports/financial-report/businessad");
    }
   
  }

  function fin_bussad_form_submit($form, &$form_state)
  {
   
   $q = array();
   $q['from-date']=$form_state['values']['bussad-from'];
   $q['to-date']=$form_state['values']['bussad-to'];

   drupal_goto("reports/financial-report/businessad", $q);
  }



