<?php
// $Id$
/**
*@file
* This file is created to show custom form creation in drupal.
*/


/**
* Implementation of hook_menu()
*/



function custom_advance_search_module_menu()
{
	$items = array();
	$items['content-type-advance-search'] = array( 'title' => t('Advance Search Node Type'),
		                           'page callback' => 'my_custom_advance_form_node',
									'access arguments' => array('access content'),
								   'type' =>MENU_CALLBACK,
									
		                          );
	
	return $items;
}

function my_custom_advance_form_node()
{
	$output = drupal_get_form('advance_form_node');

	return $output;
	
}

function advance_form_node()
{
	$option = array();
    $option['select']='select';
	$node_type_arr = array_keys(node_get_types());
	foreach($node_type_arr as $k => $v)
	{
      $option[$v]=$v;
	}
    $form['custom-data']['#tree'] = TRUE;
	$form['textfield-node-type'] = array(
										  '#title' => t('Select Node Type'),
										  '#required' => TRUE,
										  '#type'=> 'select',
										  '#weight' => -50,
		                                  '#options'=> $option,
										  '#description' => t('please select node type')
										 );
	
	
	
	$form['submit'] = array(
		                     '#type' => 'submit',
		                     '#value' => 'Search',
		                      '#weight' => -49,
		                    );

	$res = db_query("SELECT * FROM {node}");
	while($row = db_fetch_object($res))
	{
		$form['custom-data'][$row->nid] = array(
			                                     'title' => array(

												  '#type' => 'markup',

												   '#value' => $row->title,  

												),
												'description' => array(

												'#type' => 'markup',

												'#value' => $row->type,

												),
			                                    );
	}

	return $form;
}

function custom_advance_search_module_theme() {

    return array(

        'advance_form_node' => array(

            'arguments' => array('form' => NULL),
			'template' => 'custom-search-form-data',

        ),

    );
}


function advance_form_node_validate($form, &$form_state)
{
	
  if($form_state['values']['textfield-node-type']=='select')
	{
	  form_set_error('textfield-node-type', t('This type of node is not exist'));
	}
	
}

function advance_form_node_submit($form, &$form_state)
{
	print_r($form_state);
}